### PR TITLE
小改动：标准化代码

### PR DESCRIPTION
**Pull request by WhymustIhaveaname**
* Python 文件第一行从 `#!/usr/bin/python3` 改为 `#!/usr/bin/env python3`，之前的意思是用 `/usr/bin/python3` 执行，之后的意思是用用户默认的 python3 执行，看起来一样但是在碰到 anaconda 等复杂环境时只有后面那个 work。
* requirements 中不需要 `telegram==0.0.1` 也能跑，而且之前有人报告过因为安装 `telegram==0.0.1` 和 `python-telegram-bot` 名字冲突导致的环境变量问题
* 另外最新版的 `config.json` 中的注释直接运行是会报错的，这可能会坑新手

### CODE REVIEW

**Review by flynnoct — COMMENTED** [review]
Thanks for your contribution!

- The shebang change (`#!/usr/bin/python3` to `#!/usr/bin/env python3`) is reasonable, I'd like to accept this modification.
- We are going to refactor our code to split ACL, Logging modules. Deploying Logging functions to OpenAI Parser module makes no sense.
- I'd like to handle `/help` command and send a brief manual back to user. However, I'd like to do this (and also other prompts) in English.
- The reason I use `send_document` to handle generated images is which makes it possible to send full-size images but not a compressed one. I have made some attempts but they didn't work well. Maybe I will try to handle this better someday.
- About requirements.txt file, I have not tested it yet. No comments for now.
- Your comments for config template is reasonable, @RayCxggg can u handle this plz?

**Comment by WhymustIhaveaname** [comment]
我只想把前两个改动 /usr/bin/env python3、remove telegram in requirements 推给你，后面的都是我自己的更改。

后来我又加了 help、error、群中的消息一律回复、回复消息支持markdown、过长的消息拆分发送。但写得仓促就不push了

**Comment by RayCxggg** [comment]
@flynnoct @WhymustIhaveaname The template has been changed to be compliant to JSON5 specification.

**Comment by flynnoct** [comment]
@WhymustIhaveaname Thanks for your contribution. Advices accepted. Nice job.

**Pull request closed without merging**
