### PR TITLE
Add Docker method

### PR DESCRIPTION
**Pull request by EstrellaXD**
Now can use docker to deploy the bot

### CODE REVIEW

**Comment by buhe** [comment]
Nice!

**Comment by flynnoct** [comment]
Thanks for your contribution, I will review these later. I am not a Docker user, would you mind maintain these docker files with our feature updates?

**Comment by EstrellaXD** [comment]
> Thanks for your contribution, I will review these later. I am not a Docker user, would you mind maintain these docker files with our feature updates?

Of course, willing to maintain those code.

**Comment by RayCxggg** [comment]
@EstrellaXD Thanks for your contribution! We will merge the docker related code in the next release version 1.2.0.

**Comment by flynnoct** [comment]
We are going to release v1.2.0 from dev branch. There is a significant hierarchy update. Would you mind checking if the docker file works? And if it's possible to send your pull request to dev branch? Thanks!

**Comment by EstrellaXD** [comment]
> We are going to release v1.2.0 from dev branch. There is a significant hierarchy update. Would you mind checking if the docker file works? And if it's possible to send your pull request to dev branch? Thanks!

Sure, already fixed the Dockerfile and added some instructions about deployment in README.

**Review by flynnoct — APPROVED** [review]
Approved. Thanks for contribution.

**Pull request merged**
